// DO NOT EDIT THIS FILE. THIS IS PART OF THE LAYOUT.
export default function Page() {
  return (
    <div className="flex flex-col gap-4 h-full">
      <div className="flex-1 rounded-xl bg-muted/50 "></div>
    </div>
  );
}
