# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - serengpty

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: bun install, build, and test
        run: |
          bun install
          bun nx run serengpty:build

      - name: Create package.json for deployment
        run: |
          echo '{
            "name": "serengpty",
            "version": "1.0.0",
            "private": true,
            "scripts": {
              "start": "next start"
            }
          }' > ./apps/serengpty/package.json

      - name: Zip artifact for deployment
        run: zip release.zip ./node_modules ./apps/serengpty/.next ./apps/serengpty/public ./apps/serengpty/next.config.js -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7248E5954FB84A04A30969BD7D45FF68 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D2AF97130CC04220A8D15E7EE0376A0F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1A88E6FC97D542B580F96B09B2EBFD20 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'serengpty'
          slot-name: 'Production'
          package: .
